name: Auto Close Bookings

on:
  schedule:
    - cron: "30 20 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase Admin
        run: npm install firebase-admin

      # Convert secret to JSON file
      - name: Decode Firebase key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > serviceAccount.json

      # Tell Node where credentials are
      - name: Set Google Credentials
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=serviceAccount.json" >> $GITHUB_ENV

      # Run your script
      - name: Run booking closer
        run: node closeBookings.js
        



